### ISSUE TITLE
python deploy ModuleNotFoundError

### ISSUE THREAD

**Issue by long76** [heroku-python/pip-pop#22]
got error in deploy

```
File "/app/tmp/buildpacks/8790c95df255b386056ea169648fd4a33d1cb3fba81f73b536f26374f6af107145f64a5980db7a52177f63bb41527f360ebd2e3bef7b8917bda7b51cf284cfdb/vendor/pip-pop/pip-diff", line 18, in <module>
    from pip._internal.download import PipSession as session
ModuleNotFoundError: No module named 'pip._internal.download'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/tmp/buildpacks/8790c95df255b386056ea169648fd4a33d1cb3fba81f73b536f26374f6af107145f64a5980db7a52177f63bb41527f360ebd2e3bef7b8917bda7b51cf284cfdb/vendor/pip-pop/pip-diff", line 30, in <module>
    from pip.req import parse_requirements
ModuleNotFoundError: No module named 'pip.req'
```

**Comment by theodoulos** [comment]
Getting the same error since I've upgraded to python 3.6.10
